### ISSUE TITLE
Dynamic Attributes - Template variables are not parsed before evaluation

### ISSUE THREAD

**Issue by wrabit** [wrabit/django-cotton#101]
Maybe it would be good to allow this type of pattern, as raised in #100 

```html
<c-comp :list="[some_var, some_call]" />
```

Where `some_var` and `some_call` are template vars.

**Comment by ra-dave** [comment]
I think this an issue I'm also experiencing.  I'm trying to pass options from a django view for a select element on the web page.  The options are passed as a list.  Works fine if the select element is on the page but as soon as I move it into a component the options list gets treated as a single string rather than a list. 

Here's an example of just trying to display the list:

The view:
```
    options = [18, 21, 25, 30, 35, 40]
    return render(request, 'test.html', {'options': options})
```

The web page:
`<c-mycomponent :options="{{ options }}" />`

The component:
`{% for option in options %}
{{ option }}
{% endfor %}`

It works if I pass a hard-coded list to the component but obviously that's not what I need:

`<c-mycomponent :options="[18, 21]" />`

**Comment by wrabit** [comment]
`<c-mycomponent :options="{{ options }}" />` is not correct. 

Docs say `<c-mycomponent :options="options" />` for passing variables by reference. By printing with `{{` you are evaulating so it's already been printed by the time it gets to the component.

**Comment by ra-dave** [comment]
Thanks.  It's been a long day :)

**Comment by wrabit** [comment]
Addressed in latest release https://github.com/wrabit/django-cotton/releases/tag/v0.9.33
