### ISSUE TITLE
Can't use a template tag inside the component element?

### ISSUE THREAD

**Issue by ra-dave** [wrabit/django-cotton#109]
I'm trying to use a template tag to set attributes for my component, for example:

`<c-my-component {% if not is_user_logged_in %}disable{% endif %} />`

This generates a syntax error.  Can this not be supported?  I know there are other ways to accomplish what I want but the above is more "standard" django template tag usage.

**Comment by wrabit** [comment]
@ra-dave we can't manipulate attributes like we can with html elements. This is because cotton tags get compiled to native django templatetags and the compilation will not handle it. Instead, with the latest release, you can do something like:

```html
<c-my-component :disabled="{% if not is_user_logged_in %}True{% endif %}" />
```

It would be nice if it was cleaner, but it's the best I can think of for now.
