### ISSUE TITLE
Question: how to implement passthrough attrs? 

### ISSUE THREAD

**Issue by romandek** [wrabit/django-cotton#171]
Hi,

I have this setup:
 
widget/base.html
``` 
<c-vars field show_label autocomplete="off" extra_class="" container_extra_class="" />

<div>
    ...
    <input ... {{attrs}} />
    ...
</div>
``` 

display.html
```
<c-vars field show_label autocomplete="off" extra_class="" container_extra_class="" />

<c-widget.base 
    :field=field
    class="w-full {{extra_class}}" />
```

How do I pass c-display attrs object to c-widget.base? 

In 0.9.40 nothing happens with `:attrs=attrs`. In later versions seems to add some sort of a wrapper that renders to `attrs = "class="w-full "` with this odd syntax with unclosed double quote.

**Comment by wrabit** [comment]
Hi @romandek so in v1.0.0 came some changes to how we handle dynamic attributes, but the documented behaviour should not have changed. The `attrs` variable is not intended to be passed around as a component attribute, it will automatically be available to your component and contain all fallthrough / passthrough attributes.

> How do I pass c-display attrs object to c-widget.base?

They are all passed automatically inside `{{ attrs }}` but in your example attrs would be empty because both attributes you pass from the parent are defined as c-vars inside the component.

1. {{ attrs }} will catch all attributes that are not specified in c-vars
2. Should you want to set a default for an attribute, define it as a c-var then explicitly place it in your component.

Maybe the docs could be clearer about this behaviour..

**Comment by romandek** [comment]
The idea is that I wanted to retain both attrs as I pass them into some template tags. I guess I expected them to merge. 🤷 

In the end, I used `attrs` from base and passed parent attrs to base through `:extra_attrs=attrs`. Did the trick `{{ field|append_attr:extra_attrs|append_attr:attrs }}` 🤞 

Hard to say now what I was doing wrong, this was a small part of cleaning up very convoluted codebase.
