### ISSUE TITLE
Support Multiple Directories for `COTTON_DIR`

### ISSUE THREAD

**Issue by Macktireh** [wrabit/django-cotton#90]
Hi,

First of all, thank you for this project, it's really impressive and I really appreciate your work.

I was wondering if it would be possible to modify the COTTON_DIR variable to accept a list of directories instead of a single string. This would allow for specifying multiple directories, such as `layouts`, `components`, etc.

For example:

```py
COTTON_DIR = [
    "layouts",
    "components",
]
```
```
templates/
│
├── layouts/
│   ├── base.html
│   ├── dashboard.html
│   └── guest.html
│
├── components/
│   ├── navbar.html
│   ├── button.html
│   └── card.html
│
└── ...
```

Thank you in advance for considering this!

**Comment by wrabit** [comment]
Thanks for the suggestion and your support for the package! What would be the reasoning not to utilise the current approach?

```
templates/
├── cotton/
│   ├── layouts/
│   │   ├── base.html
│   │   ├── dashboard.html
│   │   └── guest.html
│   │
│   ├── components/
│   │   ├── navbar.html
│   │   ├── button.html
│   │   └── card.html
│   │
│   └── ...
│
└── ...
```

Resulting in 

```
<c-layouts.dashboard />
<c-components.card />
```

I don't think it's worth the complexity and probably more importantly losing some of the clarity by not knowing the path of the cotton component within the view.

Imagine if you arrived at the codebase and you saw `<c-button />`. You would not know if it resided in a `forms` or `ui` or `ctas` folder. It's not a situation I would like to encounter and would encourage the more explicit nature declaring the full path to keep it clear for other devs and your future self!

**Comment by Macktireh** [comment]
> What would be the reasoning not to utilise the current approach?

It's just a matter of personal preference and habit for me.

I also forked the repository and tried adapting `COTTON_DIR` with a list, but it turned out to be more complex than I initially thought. Otherwise, I agree with keeping things as they are for all the reasons you've mentioned. The simpler the approach, the fewer bugs there are likely to be 🙂.

I will close this ticket.

Thank you.

**Comment by SamuelJennings** [comment]
Hi @wrabit ,

I just found this closed issue and thought I would comment here rather than open something new. Thanks for the developing this package BTW. It has made my dev experience with Django templates so much better!

IMO, a big potential for django-cotton is the possibility to create shareable component/layout libraries. I've personally thought about creating such a thing for Bootstrap 5 as several of my Django apps share a very common layout and a single, separate package would make maintenance and updates much more efficient across all my apps.   

If I was to create such a thing, I would likely store components under the "cotton" directory and then probably (or maybe not) namespace it like so,

    templates/
    ├── cotton/
    │   ├── bs5/
    │   │   ├── base.html
    │   │   ├── button.html
    │   │   └── navbar.html
    │   │   └── ...

That way, whenever a developer encounters `<c-bs5.button text="Click me" />` in their code, they should have an idea already of where that component comes from. The problem is that this directory structure forces all users of this component library to set `COTTON_DIR = "cotton"` meaning they can no longer use their preferred directory for additional components. It's not the end of the world but allowing multiple values in COTTON_DIR (or perhaps searching for components in both "cotton/" and `COTTON_DIR`) would prevent this issue.

It's not a huge deal for me if this ability is added or not (I personally always keep components under "cotton/" anyway). Just wanted to point out a possible need for such a thing :)
