### ISSUE TITLE
"<c-" vs <C , please atleast allow both, <{Capitalized}

### ISSUE THREAD

**Issue by AhnafCodes** [wrabit/django-cotton#96]
Django-cotton is for server-side template rendering.

In my opinion it should not interfere or use an existing standard or (existing client-side library code).

Existing standard way of writing  native/pure JavaScript Component WebComponent or Custom-Elements is using a must have "-" in its name like `<my-component>`.

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#using_a_custom_element

 And there are CLIENT-side component libraries like based on Lit (used by Google and other companies) to Lightening(salesforce) which use "-" in component due to that standard/convention.

This will be a source of confusion, or worse blocker/bug, if someone already using such Client-Side 

It is would be nice if Django-Cotton atleast allows a different convention/way of  Naming components "without" a dash 
i.e. `<MyComponent>`  or `<Component>` instead of  `<c-my-component>`

**Comment by tomblancdev** [comment]
Hello, I follow this project because I find it just awesome 👍 and quite useful in today's web dev.

Maybe it could be a great idea to allow it to be set dynamically in the settings like using a `COTTON_HTML_TAG_PREFIX="c-"` or `COTTON_HTML_REGEX="^c-" `.

I don't really have time to learn how your package works for now. So I don't know if this can be possible but this is juste an idea to make it as scalable as possible.

**Comment by wrabit** [comment]
@AhnafCodes it's reasonably straight forward to implement as a non-default setting. It would be easier to make the decision if there was some consensus behind it, but I am considering it.. I guess the in-built tags would also just be available as

```html
<c-vars /> to <Vars />
<c-slot /> to <Slot />
<c-component /> to <Component />
```

**Comment by wrabit** [comment]
If this is raised again, I will revisit.
